### ISSUE TITLE
Remove unnecessary import in login

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#34]
https://github.com/Stake-And-Rope/market-app/blob/5843bbb95c5625181211e80a4305d6e857772383/pyqt5-gui/login.py#L8

**Comment by rayapetkova** [comment]
I think I can't remove the 8th row, because we need these:

![image](https://github.com/Stake-And-Rope/market-app/assets/122923696/9d01fafd-b9d6-41c2-94da-0c3315fa6d3a)
![image](https://github.com/Stake-And-Rope/market-app/assets/122923696/af557201-2355-4126-8621-c2e9a085dc64)

... or I didn't understand the assignment?

**Comment by karastoyanov** [comment]
You can add them as separate classes in the above import

```python
from PyQt5.QtWidgets import (
                            QVBoxLayout,
                            QHBoxLayout,
                            QPushButton,
                            QLabel,
                            QWidget,
                            QLineEdit
                            )
```

**Comment by rayapetkova** [comment]
Last changes: eff0fb9
Imported only the thing we need from `PyQt5.QtWidgets`, `PyQt5.QtGui` and `PyQt5.QtCore` libraries
